/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toptech;

/**
 *
 * @author TONY
 */

import javax.swing.*;
import managers.UserManager;
import managers.TicketManager;
import models.User;

public class LoginWindow extends javax.swing.JFrame {
    private UserManager userManager;
    private TicketManager ticketManager;

    public LoginWindow(UserManager userManager, TicketManager ticketManager) {
        this.userManager = userManager;
        this.ticketManager = ticketManager;
        initComponents();
        setTitle("Login");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pestana = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ingdatos = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        iconousr = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iconopss = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsuario = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bienvenidoclie = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        iconoclie = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsuarioClient = new javax.swing.JTextPane();
        ingdni = new javax.swing.JLabel();
        btnIngresarClient = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresar.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(153, 204, 255));
        btnIngresar.setText("INICIAR");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 590, 289, 58));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 512, 170, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 569, 594, 15));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 427, 394, 10));

        ingdatos.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        ingdatos.setText("INGRESE SUS DATOS");
        jPanel1.add(ingdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 516, 150, -1));

        bienvenido.setBackground(new java.awt.Color(0, 0, 51));
        bienvenido.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        bienvenido.setText("BIENVENIDOS");
        jPanel1.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 14, 394, -1));

        usuario.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        usuario.setText("USUARIO");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 337, -1, -1));

        iconousr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/usuario (3).png"))); // NOI18N
        jPanel1.add(iconousr, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 369, 40, 40));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setText("CONTRASEÑA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 443, -1, -1));

        iconopss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/llave.png"))); // NOI18N
        jPanel1.add(iconopss, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 495, 40, 40));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 386, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/LOGO.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 80, -1, 245));

        pestana.addTab("Administradores", jPanel1);

        bienvenidoclie.setBackground(new java.awt.Color(0, 0, 51));
        bienvenidoclie.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        bienvenidoclie.setText("BIENVENIDO CLIENTE");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/LOGO.jpeg"))); // NOI18N

        usuario1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        usuario1.setText("USUARIO");

        iconoclie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/usuario (3).png"))); // NOI18N

        txtUsuarioClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txtUsuarioClient);

        ingdni.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        ingdni.setText("INGRESE SU DNI");

        btnIngresarClient.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresarClient.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnIngresarClient.setForeground(new java.awt.Color(153, 204, 255));
        btnIngresarClient.setText("INICIAR");
        btnIngresarClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresarClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClientActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ingdni)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconoclie)
                .addGap(356, 356, 356))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(327, 327, 327)
                            .addComponent(usuario1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(bienvenidoclie, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel6))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bienvenidoclie)
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoclie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingdni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnIngresarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pestana.addTab("Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 695, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pestana, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 353, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 209, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUsuario.getText().trim();
        String pass = new String(txtPassword.getPassword()).trim();

        if (usuario.equals("admini") && pass.equals("admini")) {
            new MainMenuWindow(userManager, ticketManager, "ADMIN").setVisible(true);
            dispose();
            return;
        }
        User user = userManager.findUserByUsuario(usuario);
        if (user != null && user.getContrasena().equals(pass)) {
            new MainMenuWindow(userManager, ticketManager, user.getRol()).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClientActionPerformed
        // TODO add your handling code here:
        String dni = txtUsuarioClient.getText().trim();
        User usuario = userManager.findUserByDNI(dni);
        if(usuario != null && usuario.getRol().equalsIgnoreCase("CLIENTE")) {
            new ClientTicketsWindow(ticketManager, this, dni).setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "DNI incorrecto o no es cliente");
        }
    }//GEN-LAST:event_btnIngresarClientActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel bienvenidoclie;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresarClient;
    private javax.swing.JLabel iconoclie;
    private javax.swing.JLabel iconopss;
    private javax.swing.JLabel iconousr;
    private javax.swing.JLabel ingdatos;
    private javax.swing.JLabel ingdni;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane pestana;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextPane txtUsuario;
    private javax.swing.JTextPane txtUsuarioClient;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables
}
