/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toptech;


import managers.UserManager;
import managers.TicketManager;
import javax.swing.*;

public class MainMenuWindow extends javax.swing.JFrame {
    private UserManager userManager;
    private TicketManager ticketManager;
    private String rol;
    /**
     * Creates new form MainMenuWindow1
     */
    public MainMenuWindow(UserManager userManager, TicketManager ticketManager, String rol) {
        this.userManager = userManager;
        this.ticketManager = ticketManager;
        this.rol = rol;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menú Principal");
        configurarOpcionesPorRol();
    }
    

    public MainMenuWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menú Principal");
    }
    
    private void configurarOpcionesPorRol() {
        // Si el usuario es ADMINI, muestra todo
        if ("ADMIN".equalsIgnoreCase(rol)) {
            // Todo visible
            btncrearusuario.setVisible(true);
            btnmodificarusuario.setVisible(true);
            btnlistadeusuarios.setVisible(true);
        } else if ("TECNICO".equalsIgnoreCase(rol)) {
            // Oculta las opciones de usuario (solo tickets para técnico)
            btncrearusuario.setVisible(false);
            btnmodificarusuario.setVisible(false);
            btnlistadeusuarios.setVisible(false);
            // Si tienes otras opciones solo para admin, ocúltalas
        }
        // Mensaje de bienvenida:
        bienvenido.setText("Bienvenido, " + rol);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoceleste = new javax.swing.JPanel();
        opcionusuario = new javax.swing.JPanel();
        btnAtendidos1 = new javax.swing.JButton();
        btncrearusuario = new javax.swing.JButton();
        btnmodificarusuario = new javax.swing.JButton();
        btnlistadeusuarios = new javax.swing.JButton();
        opcionticket = new javax.swing.JPanel();
        btncrearticket = new javax.swing.JButton();
        btnmodificarticket = new javax.swing.JButton();
        btnlistadeticket = new javax.swing.JButton();
        bienvenido = new javax.swing.JLabel();
        toptech = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoceleste.setBackground(new java.awt.Color(153, 204, 255));
        fondoceleste.setForeground(new java.awt.Color(0, 0, 204));
        fondoceleste.setPreferredSize(new java.awt.Dimension(850, 560));

        opcionusuario.setBackground(new java.awt.Color(51, 102, 255));
        opcionusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        opcionusuario.setForeground(new java.awt.Color(255, 255, 255));

        btnAtendidos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtendidos1.setText("GESTIÓN TICKETS");
        btnAtendidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendidos1ActionPerformed(evt);
            }
        });

        btncrearusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncrearusuario.setText("CREAR USUARIO");
        btncrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearusuarioActionPerformed(evt);
            }
        });

        btnmodificarusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmodificarusuario.setText("MODIFICAR USUARIO");
        btnmodificarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarusuarioActionPerformed(evt);
            }
        });

        btnlistadeusuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlistadeusuarios.setText("LISTA DE USUARIOS");
        btnlistadeusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistadeusuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionusuarioLayout = new javax.swing.GroupLayout(opcionusuario);
        opcionusuario.setLayout(opcionusuarioLayout);
        opcionusuarioLayout.setHorizontalGroup(
            opcionusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionusuarioLayout.createSequentialGroup()
                .addGroup(opcionusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, opcionusuarioLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btncrearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnmodificarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnlistadeusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(opcionusuarioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnAtendidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        opcionusuarioLayout.setVerticalGroup(
            opcionusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionusuarioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(opcionusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrearusuario)
                    .addComponent(btnmodificarusuario)
                    .addComponent(btnlistadeusuarios))
                .addGap(433, 433, 433)
                .addComponent(btnAtendidos1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        opcionticket.setBackground(new java.awt.Color(51, 102, 255));
        opcionticket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Tickets", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        opcionticket.setForeground(new java.awt.Color(255, 255, 255));

        btncrearticket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncrearticket.setText("CREAR TICKET");
        btncrearticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearticketActionPerformed(evt);
            }
        });

        btnmodificarticket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmodificarticket.setText("MODIFICAR TICKET");
        btnmodificarticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarticketActionPerformed(evt);
            }
        });

        btnlistadeticket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlistadeticket.setText("LISTA DE TICKET");
        btnlistadeticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistadeticketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionticketLayout = new javax.swing.GroupLayout(opcionticket);
        opcionticket.setLayout(opcionticketLayout);
        opcionticketLayout.setHorizontalGroup(
            opcionticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionticketLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btncrearticket, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(btnmodificarticket, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btnlistadeticket, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        opcionticketLayout.setVerticalGroup(
            opcionticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionticketLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(opcionticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrearticket)
                    .addComponent(btnlistadeticket)
                    .addComponent(btnmodificarticket))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        bienvenido.setBackground(new java.awt.Color(0, 0, 0));
        bienvenido.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        bienvenido.setText("BIENVENIDO");

        toptech.setBackground(new java.awt.Color(0, 0, 0));
        toptech.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        toptech.setText("top tech");

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        separador.setBackground(new java.awt.Color(51, 102, 255));
        separador.setForeground(new java.awt.Color(51, 102, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/LOGO.jpg"))); // NOI18N

        Separador.setBackground(new java.awt.Color(51, 102, 255));
        Separador.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout fondocelesteLayout = new javax.swing.GroupLayout(fondoceleste);
        fondoceleste.setLayout(fondocelesteLayout);
        fondocelesteLayout.setHorizontalGroup(
            fondocelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondocelesteLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(toptech))
            .addGroup(fondocelesteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondocelesteLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(opcionusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondocelesteLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(opcionticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondocelesteLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addGroup(fondocelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addComponent(logo))
        );
        fondocelesteLayout.setVerticalGroup(
            fondocelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondocelesteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(toptech)
                .addGap(6, 6, 6)
                .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(opcionusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(opcionticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(fondocelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondocelesteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        opcionticket.getAccessibleContext().setAccessibleName("Opciones de Tickets\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondoceleste, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondoceleste, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtendidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendidos1ActionPerformed
        // TODO add your handling code here:
        new ListTicketsWindow(ticketManager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAtendidos1ActionPerformed

    private void btncrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearusuarioActionPerformed
        // TODO add your handling code here:
        new CreateUserWindow(userManager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncrearusuarioActionPerformed

    private void btnmodificarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarusuarioActionPerformed
        // TODO add your handling code here:
        new ModifyUserWindow(userManager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnmodificarusuarioActionPerformed

    private void btnlistadeusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistadeusuariosActionPerformed
        // TODO add your handling code here :
        new ListUsersWindow(userManager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnlistadeusuariosActionPerformed

    private void btncrearticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearticketActionPerformed
        new CreateTicketWindow(ticketManager, userManager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncrearticketActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new LoginWindow(userManager, ticketManager).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnmodificarticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarticketActionPerformed
        // TODO add your handling code here:
        new ModifyTicketWindow(ticketManager, userManager, this, rol).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnmodificarticketActionPerformed

    private void btnlistadeticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistadeticketActionPerformed
        // TODO add your handling code here:
        new ListTicketsWindow(ticketManager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnlistadeticketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton btnAtendidos1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btncrearticket;
    private javax.swing.JButton btncrearusuario;
    private javax.swing.JButton btnlistadeticket;
    private javax.swing.JButton btnlistadeusuarios;
    private javax.swing.JButton btnmodificarticket;
    private javax.swing.JButton btnmodificarusuario;
    private javax.swing.JPanel fondoceleste;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel opcionticket;
    private javax.swing.JPanel opcionusuario;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel toptech;
    // End of variables declaration//GEN-END:variables
}
