package toptech;

import javax.swing.*;
import managers.UserManager;
import models.User;
import java.awt.event.*;
import utils.JTextFieldLimit;

public class ModifyUserWindow extends javax.swing.JFrame {

    /**
     * Creates new form ModifyUserWindow1
     */
    private UserManager userManager;
    private JFrame parentWindow;

    // Constructor principal y ventana padre
    public ModifyUserWindow(UserManager userManager, JFrame parentWindow) {
        this.userManager = userManager;
        this.parentWindow = parentWindow;
        initComponents();
        setTitle("Modificar Usuario");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        ((javax.swing.text.AbstractDocument) jPassword.getDocument()).setDocumentFilter(new JTextFieldLimit(6));

        // Muestra/oculta contraseña
        btnmostrar.addActionListener(e -> {
            if (btnmostrar.isSelected()) {
                jPassword.setEchoChar((char) 0);
            } else {
                jPassword.setEchoChar('\u2022');
            }
        });

        //CARGAR USUARIOS EN EL COMBOBOX
        cargarUsuariosEnComboBox();
    }

    public ModifyUserWindow() {
        initComponents();
    }

    private void cargarUsuariosEnComboBox() {
        if (userManager == null) {
            return;
        }

        // Limpiar ComboBox
        jComboBox1.removeAllItems();

        // Agregar opción vacía inicial
        jComboBox1.addItem("-- Seleccione un usuario --");

        // Obtener todos los usuarios
        User[] usuarios = userManager.getAllUsers();

        // Agregar cada usuario al ComboBox (mostrar su nombre de usuario)
        for (User user : usuarios) {
            jComboBox1.addItem(user.getUsuario());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtapellido = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtnombre1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtapellido1 = new javax.swing.JTextPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txttoptech = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtcontraseña = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        btnmostrar = new javax.swing.JCheckBox();
        txtnombre = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtdni1 = new javax.swing.JTextPane();
        roles = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtusuariogenerado = new javax.swing.JTextPane();
        txtDNI = new javax.swing.JLabel();
        txtrol1 = new javax.swing.JLabel();
        txtmodificarusuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtcontraseña1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator2.setBackground(new java.awt.Color(51, 102, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1030, 607));
        jPanel1.setMinimumSize(new java.awt.Dimension(1030, 607));
        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 10, 650));

        txtapellido.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtapellido.setText("APELLIDO");
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jScrollPane6.setViewportView(txtnombre1);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 237, 198, -1));

        jScrollPane4.setViewportView(txtapellido1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 273, 198, -1));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 102, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 439, 730, 20));

        btnSalir.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 90, 36));

        btnVolver.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 94, 36));

        txttoptech.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        txttoptech.setText("top tech");
        jPanel1.add(txttoptech, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 98, 35));

        btnGuardar.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, 35));

        txtcontraseña.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtcontraseña.setText("USUARIOS CREADOS:");
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 110, -1));

        btnmostrar.setText("MOSTRAR");
        jPanel1.add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        txtnombre.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtnombre.setText("NOMBRE");
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jScrollPane5.setViewportView(txtdni1);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 150, -1));

        roles.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "ADMINISTRADOR", "TECNICO" }));
        roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolesActionPerformed(evt);
            }
        });
        jPanel1.add(roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 359, -1, -1));

        jScrollPane7.setViewportView(txtusuariogenerado);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, -1));

        txtDNI.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtDNI.setText("D.N.I");
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 20));

        txtrol1.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtrol1.setText("ROL");
        jPanel1.add(txtrol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 369, -1, -1));

        txtmodificarusuario.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtmodificarusuario.setText("MODIFICAR USUARIO");
        jPanel1.add(txtmodificarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtusuario.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtusuario.setText("# USUARIO");
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 102, 255));
        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/LOGO.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        txtcontraseña1.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        txtcontraseña1.setText("CONTRASEÑA");
        jPanel1.add(txtcontraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaUser(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(792, 792, 792)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        if (parentWindow != null) {
            parentWindow.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (userManager == null) {
            return;
        }

        String username = txtusuariogenerado.getText().trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre de usuario.");
            return;
        }

        User u = userManager.findUserByUsuario(username);

        if (u != null) {
            // Usuario encontrado - llenar campos
            txtnombre1.setText(u.getNombre());
            txtapellido1.setText(u.getApellido());
            txtdni1.setText(u.getDni());
            jPassword.setText(""); // Por seguridad no se muestra la contraseña

            if (u.getRol().equalsIgnoreCase("ADMIN")) {
                roles.setSelectedItem("ADMINISTRADOR");
            } else {
                roles.setSelectedItem("TECNICO");
            }

            JOptionPane.showMessageDialog(this, "Usuario encontrado correctamente.");
        } else {
            // Usuario NO encontrado - limpiar campos
            txtnombre1.setText("");
            txtapellido1.setText("");
            txtdni1.setText("");
            jPassword.setText("");
            roles.setSelectedItem("SELECCIONE");

            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (parentWindow != null) {
            parentWindow.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (userManager == null) {
            return;
        }

        String username = txtusuariogenerado.getText().trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre de usuario para buscar.");
            return;
        }

        User u = userManager.findUserByUsuario(username);

        if (u != null) {
            // Usuario encontrado - llenar campos
            txtnombre1.setText(u.getNombre());
            txtapellido1.setText(u.getApellido());
            txtdni1.setText(u.getDni());
            jPassword.setText(""); // Por seguridad no se muestra la contraseña

            if (u.getRol().equalsIgnoreCase("ADMIN")) {
                roles.setSelectedItem("ADMINISTRADOR");
            } else {
                roles.setSelectedItem("TECNICO");
            }

            JOptionPane.showMessageDialog(this, "Usuario encontrado correctamente.");
        } else {
            // Usuario NO encontrado - limpiar campos
            txtnombre1.setText("");
            txtapellido1.setText("");
            txtdni1.setText("");
            jPassword.setText("");
            roles.setSelectedItem("SELECCIONE");

            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void ListaUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaUser
        if (userManager == null) {
            return;
        }

        String selectedItem = (String) jComboBox1.getSelectedItem();

        // Si no hay selección o es la opción inicial, no hacer nada
        if (selectedItem == null || selectedItem.equals("-- Seleccione un usuario --")) {
            limpiarCampos();
            return;
        }

        // Buscar el usuario seleccionado
        User u = userManager.findUserByUsuario(selectedItem);

        if (u != null) {
            // Llenar campos automáticamente
            txtusuariogenerado.setText(u.getUsuario());
            txtnombre1.setText(u.getNombre());
            txtapellido1.setText(u.getApellido());
            txtdni1.setText(u.getDni());
            jPassword.setText(""); // Por seguridad no mostrar contraseña

            if (u.getRol().equalsIgnoreCase("ADMIN")) {
                roles.setSelectedItem("ADMINISTRADOR");
            } else {
                roles.setSelectedItem("TECNICO");
            }
        }
    }//GEN-LAST:event_ListaUser

    private void limpiarCampos() {
        txtusuariogenerado.setText("");
        txtnombre1.setText("");
        txtapellido1.setText("");
        txtdni1.setText("");
        jPassword.setText("");
        roles.setSelectedItem("SELECCIONE");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyUserWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox btnmostrar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> roles;
    private javax.swing.JLabel txtDNI;
    private javax.swing.JLabel txtapellido;
    private javax.swing.JTextPane txtapellido1;
    private javax.swing.JLabel txtcontraseña;
    private javax.swing.JLabel txtcontraseña1;
    private javax.swing.JTextPane txtdni1;
    private javax.swing.JLabel txtmodificarusuario;
    private javax.swing.JLabel txtnombre;
    private javax.swing.JTextPane txtnombre1;
    private javax.swing.JLabel txtrol1;
    private javax.swing.JLabel txttoptech;
    private javax.swing.JLabel txtusuario;
    private javax.swing.JTextPane txtusuariogenerado;
    // End of variables declaration//GEN-END:variables
}
